### ISSUE TITLE
How to take care of your eyes?

### ISSUE THREAD

**Issue by BosEriko** [mikeal/self-care#5]

**Comment by michaeljaltamirano** [comment]
I like to follow the [20-20-20 rule](https://www.healthline.com/health/eye-health/20-20-20-rule). I've been fortunate that my eyesight has not degraded that much in the last couple years since trying to consciously follow it--failing often, of course!--and some of it must be attributable to it.

**Comment by Anathk60** [comment]
Dark theme everything.
Brightness 0 - 25%

**Comment by anathkantonda** [comment]
Dark theme everything
Brightness 0 - 25%

**Comment by TimonVS** [comment]
Thanks so much @mikeal for creating this repository to make me aware of this and thanks @mjaltamirano for your great suggestion 🙇‍♂️. I'm prone to forget these types of things when I'm in the flow, so I found this article which reviews 3 Mac apps to help you with the 20-20-20 rule: https://medium.com/breaks-for-eyes/these-3-simple-mac-apps-will-help-you-take-breaks-and-get-rid-of-eye-strain-7d99e98a8719. I'm personally using Time Out now as it is very configurable to your workflow.

**Comment by slurmulon** [comment]
I have found that UV glare protection glasses (such as Gunnars) help me out significantly.

Not a replacement for the 20-20-20 rule, but certainly complementary!

**Comment by matthewpoer** [comment]
Blue-light filtering glasses. Currently using [Umizato Zephyr](https://umizato.com/products/zephyr?variant=12250924286032). Look decent, feel good and definitely help, especially on late work nights.

One thing to note with them though: you have to wear from the start of your computing day. If you wait until your eyes feel like they're bleeding to get up and put them on they're not going to help. ("duh" you say, and you're right, but I had to learn it).

If you have Rx glasses you can get a coating that does the same thing (Lenscrafters calls it "BlueIQ"). My dad also got himself some "readers" (the 1.5x zoom with no real Rx) that had the blue-light filter so he can read books on his iPad.

**Comment by slurmulon** [comment]
> One thing to note with them though: you have to wear from the start of your computing day. If you wait until your eyes feel like they're bleeding to get up and put them on they're not going to help. ("duh" you say, and you're right, but I had to learn it).

Now that you mention it, I've realized this is totally true.

Sometimes I wait until it gets dark to wear them and they're not nearly as effective.

Thanks for that insight!

**Comment by asgartech** [comment]
Rather than using an 8pt font (or smaller) to fit as much code as possible into the screen, I use a 14-16pt font and accept that I'll have to scroll. I also favor serif monospace fonts (Go Mono is nice) over sans-serif monospace fonts; I find them more comfortable to read.

**Comment by troy0820** [comment]
Yeah, I use the Felix Grays UV "computer" glasses and they've helped out a lot.  I also keep a desk light that seems to help with overall lighting.

**Comment by MikeMcQuaid** [comment]
I'm sure none of this is anything but a placebo but:
- use Night Shift/Flux on all my devices
- set the screen brightness on my devices as low as I can comfortably handle

**Comment by TehShrike** [comment]
I actually visited an eye doctor last week for the first time in decades, and she said:

- Night Shift/Flux is not a placebo, she recommended turning it on all the time, not just after sundown (I haven't gone that far yet...)
- She recommended glasses that block certain wavelengths of blue light – when I bought my (first ever!) glasses, I got ones with [this stuff 🌿](http://www.uv420cut.com/faq/) built into the lenses
- They had a big machine that takes pictures of inside of your eyes.  It showed that my water ducts were not all making it to the edge of my eyelids like they're supposed to.  Apparently that's become common in the last 20 years as more people are spending much of their day looking at screens.

Apparently it's a function of not blinking fully/often enough, and it can lead to dry eyes later in life, which is super hard to fix.  She recommended something [like this](https://youtu.be/hOGwoBD_-sY) once or twice a day to get the eye water flowing.

She also said to make sure to blink often, and fully, since apparently a lot of people do half-blinks where your top eyelids don't go all the way down and coat the full eye with liquid.

**Comment by sashafirsov** [comment]
Strange, the eye exercise have not  mentioned. Worked for me when I could not keep to focus more than 20 minutes. I know people who actually fixed their eye sight with this exercise: focus on far distance details, once fixed, focus on close (1 foot) details. Do it 20 times. 

Eyes after that feels tired, but ability to focus restored. I need to repeat it once in 20 minutes if not coding but reading from screen. The enjoyable view in window helps a lot. If there is no window, usually I quit for one or another unrelated reason.

**Comment by yedpodtrzitko** [comment]
One important thing - dont rub your eyes! The friction slowly but surely leads to [Keratokonus](https://en.wikipedia.org/wiki/Keratoconus) and there's no way back. I used to rub my eyes a lot when I was younger (due to allergy), and now I have a slightly doubled vision on one of my eyes due to keratokonus...

**Comment by BosEriko** [comment]
@yedpodtrzitko no going back? For real? Oh no. That explains why I get double vision in cinemas. I usually rub my eyes at night when its too tired. My poor eyes.

**Comment by yedpodtrzitko** [comment]
@BosEriko I'd rather recommend you to visit a hospital / eye clinic, they'll sure tell you better than a stranger on the internet would.
